#!/usr/bin/env python3
"""Emit a DBML (.erd) file from the same JSON spec used by render_erd.py / build_data_dictionary.py.

DBML (Database Markup Language, https://dbml.dbdiagram.io) is a portable, text-based ER-model
source: it round-trips with dbdiagram.io and the `@dbml/cli` toolchain (dbml2sql / sql2dbml) and
diffs cleanly in git. This writes the model as DBML so the ERD lives as editable text alongside the
.drawio picture, the DDL, and the data dictionary.

Usage:
    python build_dbml.py --spec SPEC.json --out "data-model/ERD.erd"

Spec shape — see render_erd.py's docstring for the full shape. This script reads:
  title
  entities[].name, entities[].kind ("dim"|"fact"|"bridge"|"table")
  entities[].attributes[]: name, type, pk (bool), fk (bool), fk_ref ("table.column"),
                           nullable (bool), business_definition, source_system, scd_type, notes
  relationships[]: from, to, from_attr, to_attr, cardinality, label

Pure standard library.
"""
import argparse, json, re, sys

# spec cardinality -> DBML relationship operator (written as  from <op> to )
CARD_OP = {
    "many-to-one": ">",
    "one-to-many": "<",
    "one-to-one": "-",
    "many-to-many": "<>",
}

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def ident(name):
    """A bare DBML identifier, or a double-quoted one if it has spaces/specials."""
    name = str(name)
    return name if IDENT_RE.match(name) else '"%s"' % name.replace('"', '')


def note_str(text):
    """A DBML note literal. Triple-single-quotes tolerate embedded quotes and newlines."""
    text = str(text).replace("'''", "''")
    return "'''%s'''" % text


def col_type(t):
    """DBML stores the type as a token; quote it if it contains spaces or odd chars."""
    t = (t or "").strip() or "varchar"
    return t if re.match(r'^[A-Za-z0-9_,()\[\]. ]+$', t) and " " not in t else '"%s"' % t.replace('"', '')


def _pair(ta, ca, tb, cb):
    """Direction-agnostic key for one relationship's endpoints."""
    return frozenset(("%s.%s" % (ta, ca), "%s.%s" % (tb, cb)))


def build(spec):
    title = spec.get("title", "Data Model")
    entities = spec.get("entities", [])
    relationships = spec.get("relationships", [])

    # endpoints already covered by an explicit Ref line — so a column's inline
    # ref: isn't emitted too (dbdiagram.io rejects duplicate references).
    rel_pairs = set()
    for r in relationships:
        if r.get("from") and r.get("to") and r.get("from_attr") and r.get("to_attr"):
            rel_pairs.add(_pair(r["from"], r["from_attr"], r["to"], r["to_attr"]))

    out = []
    out.append("// %s" % title)
    out.append("// DBML ER model — generated by the data-model skill.")
    out.append("// Edit at dbdiagram.io, or run through @dbml/cli (dbml2sql / sql2dbml).")
    out.append("")

    for e in entities:
        ename = e["name"]
        header = "Table %s {" % ident(ename)
        out.append(header)
        for a in e.get("attributes", []):
            settings = []
            if a.get("pk"):
                settings.append("pk")
            if a.get("nullable") is False and not a.get("pk"):
                settings.append("not null")
            # column-level FK ref keeps the relationship visible even without a Ref
            # line — but only when no explicit Ref already covers these endpoints.
            if a.get("fk") and a.get("fk_ref"):
                m = str(a["fk_ref"]).split(".")
                if len(m) == 2 and _pair(ename, a["name"], m[0], m[1]) not in rel_pairs:
                    settings.append("ref: > %s.%s" % (ident(m[0]), ident(m[1])))
            meta = []
            if a.get("scd_type"):
                meta.append("SCD %s" % a["scd_type"])
            if a.get("source_system"):
                meta.append("src: %s" % a["source_system"])
            note_bits = [b for b in [a.get("business_definition", "").strip()] if b] + meta
            if note_bits:
                settings.append("note: %s" % note_str(" — ".join(note_bits)))
            line = "  %s %s" % (ident(a["name"]), col_type(a.get("type")))
            if settings:
                line += " [%s]" % ", ".join(settings)
            out.append(line)
        # table-level note carrying the kind, so star-schema roles survive the round-trip
        kind = e.get("kind")
        if kind and kind != "table":
            out.append("  Note: %s" % note_str("kind: %s" % kind))
        out.append("}")
        out.append("")

    # explicit relationships (in addition to any inline column refs above)
    ref_lines = []
    for r in relationships:
        op = CARD_OP.get(str(r.get("cardinality", "")).lower(), ">")
        fa, ta = r.get("from_attr"), r.get("to_attr")
        if not (r.get("from") and r.get("to") and fa and ta):
            print("Warning: skipping incomplete relationship: %r" % r, file=sys.stderr)
            continue
        line = "Ref: %s.%s %s %s.%s" % (
            ident(r["from"]), ident(fa), op, ident(r["to"]), ident(ta))
        if r.get("label"):
            line += "  // %s" % r["label"]
        ref_lines.append(line)
    if ref_lines:
        out.append("// Relationships")
        out.extend(ref_lines)
        out.append("")

    # group facts/dims/bridges for readability where kinds are present
    groups = {}
    for e in entities:
        k = e.get("kind", "table")
        groups.setdefault(k, []).append(e["name"])
    if any(k in groups for k in ("fact", "dim", "bridge")):
        for k in ("fact", "dim", "bridge", "table"):
            if groups.get(k):
                out.append("TableGroup %s {" % ident(k + "s"))
                for n in groups[k]:
                    out.append("  %s" % ident(n))
                out.append("}")
                out.append("")

    return "\n".join(out).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description="Emit a DBML (.erd) file from the data-model JSON spec.")
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", required=True, help="Output .erd path (DBML syntax)")
    args = ap.parse_args()
    with open(args.spec, encoding="utf-8") as f:
        spec = json.load(f)
    dbml = build(spec)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(dbml)
    print("Wrote DBML: %s" % args.out)


if __name__ == "__main__":
    main()
